# CodeRabbit Configuration for AI Automation Pipeline
# Optimized for CodeRabbit → Copilot → OpenHands workflow

language: en-US
tone_instructions: 'Professional, technical, and actionable. Focus on implementation details.'

reviews:
  request_changes_workflow: true
  profile: assertive
  high_level_summary: true
  review_status: true
  poem: false
  collapse_walkthrough: false

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - develop

  path_instructions:
    - path: '**.ts'
      instructions: |
        - Ensure strict TypeScript typing
        - Check for proper error handling
        - Verify null safety
        - Suggest type guards where appropriate

    - path: '**.tsx'
      instructions: |
        - Check React best practices
        - Verify proper hook usage
        - Ensure accessibility (a11y)
        - Check for prop type definitions

    - path: '**.test.{ts,tsx,js,jsx}'
      instructions: |
        - Verify test coverage for edge cases
        - Check for proper mocking
        - Ensure tests are deterministic
        - Validate assertion messages

    - path: '**/workflows/**.yml'
      instructions: |
        - Verify GitHub Actions syntax
        - Check for security best practices
        - Validate secret usage
        - Ensure proper error handling

chat:
  auto_reply: true

knowledge_base:
  learnings:
    enabled: true
  opt_out: false

code_generation:
  enabled: true
  include_full_functions: true
  provide_alternatives: true

ignore:
  - '**/*.min.js'
  - '**/*.min.css'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/node_modules/**'
  - '**/.next/**'
  - '**/.cache/**'
  - '**/package-lock.json'
  - '**/yarn.lock'
  - '**/pnpm-lock.yaml'

early_access: true
